trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '65c3da8b-ea03-4747-8835-8d486862b420'
  aksClusterName: 'eShopOnContainers'
  resourceGroupName: 'tmp-2020'
  containerRegistry: 'tmp2020.azurecr.io'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Deploy
  displayName: Deploy stage

  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
      steps:
      - script: "s/deploy/k8s/helm/deploy-all-mac.ps1 -externalDns aks -aksName $(aksClusterName) -aksRg $(resourceGroupName) -imageTag linux-dev -useMesh $false"
        name: Helm deploy