trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '65c3da8b-ea03-4747-8835-8d486862b420'
  aksClusterName: 'eShopOnContainers'
  resourceGroupName: 'tmp-2020'
  containerRegistry: 'tmp2020.azurecr.io'
  # Agent VM image name
  vmImageName: 'ubuntu-16.04'

stages:
- stage: Deploy
  displayName: Deploy stage
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: "Development"
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:      
          steps:
          - checkout: self
          - task: Docker@2
            inputs:
              containerRegistry: 'tmp2020'
              command: 'login'
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: 'Azure subscription 1(1)(bbeb73e1-c85a-4b87-934f-8bed6c3801c1)'
              ScriptType: 'InlineScript'
              Inline: 'deploy/k8s/helm/deploy-all-mac.ps1 -externalDns aks -aksName $(aksClusterName) -aksRg $(resourceGroupName) -imageTag linux-dev -registry $(containerRegistry) -useMesh $false'
              azurePowerShellVersion: 'LatestVersion'