trigger:
- master

resources:
- repo: self

variables:
  aksClusterName: 'eShopOnContainers'
  resourceGroupName: 'tmp-2020'
  
  servicePrincipalUserName: '787362c4-2617-4e33-81db-133d1cf1bd79'
  servicePrincipalTenantId: 'b41b72d0-4e9f-4c26-8a69-f949f367c91d'
  
  # Agent VM image name
  vmImageName: 'ubuntu-16.04'

stages:
- stage: Deploy
  displayName: Deploy stage
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: "Development"
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:      
          steps:
          - checkout: self
          - script: az login --service-principal --username $(servicePrincipalUserName) --tenant $(servicePrincipalTenantId) --password $CERTIFICATE_PATH
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: 'Azure subscription 1(1)(bbeb73e1-c85a-4b87-934f-8bed6c3801c1)'
              ScriptType: 'InlineScript'
              Inline: 'deploy/k8s/helm/deploy-all-mac.ps1 -externalDns aks -aksName $(aksClusterName) -aksRg $(resourceGroupName) -imageTag linux-dev -useMesh $false'
              FailOnStandardError: true
              azurePowerShellVersion: 'LatestVersion'
          