trigger:
- master

resources:
- repo: self

variables:
  aksClusterName: 'eShopOnContainers'
  resourceGroupName: 'tmp-2020'
  # Agent VM image name
  vmImageName: 'ubuntu-16.04'

stages:
- stage: Deploy
  displayName: Deploy stage
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: "Development"
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:      
          steps:
          - checkout: self
          - script: az login --service-principal --username $(sericePrincipalAppId) --tenant $(servicePrincipalTenantId) --password $(servicePrincipalPassword)
          - script: az aks get-credentials --resource-group $(resourceGroupName) --name $(aksClusterName)
          - task: HelmInstaller@0
            inputs:
              helmVersion: '3.2.4'
              installKubectl: true
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: 'Azure subscription 1(bbeb73e1-c85a-4b87-934f-8bed6c3801c1)'
              ScriptType: 'InlineScript'
              Inline: 'deploy/k8s/helm/deploy-all-mac.ps1 -externalDns aks -aksName $(aksClusterName) -aksRg $(resourceGroupName) -imageTag linux-dev -useMesh $false'
              FailOnStandardError: true
              azurePowerShellVersion: 'LatestVersion'
          